import os
import re

files = [
    'blog/index.html',
    'blog/kalkulator-etf-jak-obliczyc-realny-zysk.html',
    'blog/_article-template.html'
]

# Patterns to replace. 
# We'll use regex to match combinations regardless of order, but simple string replacement is safer where possible.
# Let's define the precise strings found in the blog pages.
replacements = {
    'bg-slate-50 dark:bg-slate-950': 'bg-stitch-bg',
    'bg-white dark:bg-slate-900': 'bg-stitch-surface',
    'border-slate-200 dark:border-slate-800/50': 'border-stitch-border/50',
    'border-slate-200 dark:border-slate-800': 'border-stitch-border',
    'border-slate-100 dark:border-slate-800': 'border-stitch-border',
    'border-slate-100 dark:border-slate-900': 'border-stitch-border',
    'text-slate-900 dark:text-white': 'text-stitch-text',
    'text-slate-800 dark:text-slate-200': 'text-stitch-text',
    'text-slate-600 dark:text-slate-300': 'text-stitch-muted',
    'text-slate-700 dark:text-slate-300': 'text-stitch-muted',
    'text-slate-500 dark:text-slate-400': 'text-stitch-muted',
    'shadow-sm': 'shadow-stitch-soft',
    'dark:text-slate-100': '', # remove redundant dark text overrides if they exist
    'dark:bg-slate-950': ''
}

for path in files:
    if not os.path.exists(path):
        continue
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
        
    original = content
        
    for old, new in replacements.items():
        content = content.replace(old, new)
        
    # Clean up any double spaces generated by replacing with empty string
    content = content.replace('  ', ' ')
    content = content.replace('class=" ', 'class="')
    content = content.replace(' "', '"')
        
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print(f"Refactored {path}")

